Add Multistep Beg Yearly form component
wmde/fundraising-banners-until-2022 pull request #1056
Opened 2022-10-07 11:45 UTC by Abban

This component is to be used in banners that implement this year's 2 step process

2022-10-07 11:56 UTC, moiikana commented
might already make sense at this point to have a `components/DonationForm/Forms/` folder to put in the different donation form implementations

2022-10-07 12:01 UTC, moiikana requested changes

2022-10-07 12:01 UTC, moiikana commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +	const [ alternative, setAlternative, alternativeValidity, setAlternativeValidity ] = useAlternate( null );
maybe it is possible to describe / rename that hook here, or add an explanatory comment in the hook js file to describe what it is doing, because `Alternative` leaves a lot of question marks in my head when browsing the code

2022-10-07 12:06 UTC, moiikana requested changes

2022-10-07 12:06 UTC, moiikana commented on components/DonationForm/hooks/use_alternative.js
> +export default function useAddressType( initial ) {
function title has to change, it's still useAddressType

2022-10-07 12:10 UTC, Abban commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +	const [ alternative, setAlternative, alternativeValidity, setAlternativeValidity ] = useAlternate( null );
The field is called alternative, though. The second step is basically "hey we got your choices, would you like to do this instead?"

2022-10-07 15:19 UTC, moiikana commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +	const [ alternative, setAlternative, alternativeValidity, setAlternativeValidity ] = useAlternate( null );
I tried to come up with an alternative to Alternative. I think in my mind it would be more like `SuggestedValue` or something like that. Or `SuggestedAlternative`, even though it should of course be kept short.
`Alternative` feels a slight bit too ambiguous as a name/identifier in code for me.
I would like to have another opinion on it by @gbirke and/or @TanujaDoriya, then I'll approve

2022-10-10 16:32 UTC, gbirke commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +	const [ alternative, setAlternative, alternativeValidity, setAlternativeValidity ] = useAlternate( null );
I also find the name "Alternative" too ambiguous. I like the hook for a "binary state" (that in reality is a trinary state because it can also be  "Unset") - we can reuse that for other options. Suggested names (for the state, use `use_`, `set` `validity` prefixes/suffixes as needed): `binaryState`, `yesNoState`, `twoOptionsState`, `twoAlternativesState`, etc

2022-10-10 16:36 UTC, gbirke commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +	const [ alternative, setAlternative, alternativeValidity, setAlternativeValidity ] = useAlternate( null );
When using the hook, we should also name the variables after the domain thing they represent, e.g. 
```js
const [ hasUpgradedToRecurring, upgradeToRecurring, upgradeToRecurringIsValid, setupgradeToRecurringValidity ] = useYesNoState( null );
```

2022-10-11 07:31 UTC, Abban commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +	const [ alternative, setAlternative, alternativeValidity, setAlternativeValidity ] = useAlternate( null );
I don't get why this is an issue now after being used for in multiple banners in the last campain (and maybe the one before)? `yesNoState` means even less than `alternative`

2022-10-11 07:48 UTC, Abban commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +	const [ alternative, setAlternative, alternativeValidity, setAlternativeValidity ] = useAlternate( null );
This brance is rebased into multiple current banners now so this change will have to be made in another PR. I made a ticket for it. https://phabricator.wikimedia.org/T320467

2022-10-12 08:40 UTC, gbirke commented on components/DonationForm/BegYearlyRecurringDonationForm.jsx
> +			<FormStep2
Anticipating the mobile banner with a different implementation/ markup of the choices (buttons instead of radio buttons), you could make this a prop and pass it in from the banner component. But maybe that's premature, so I just want to point that out.

2022-10-19 08:45 UTC, Abban commented
This can be merged now if someone can re-re-review it

2022-10-27 10:24 UTC, gbirke approved these changes

2022-10-27 11:37 UTC, merged