Add Mr Satan theme
wmde/fundraising-banners-until-2022 pull request #1066
Opened 2022-10-10 12:13 UTC by Abban

This is used on the iPad and WPDE desktop banners

2022-10-10 19:27 UTC, gbirke requested changes
I find it hard to review without an example

2022-10-11 04:48 UTC, Abban commented
Ah right, I was shooting through all these PRs and didn't think about that. It's being used in https://github.com/wmde/fundraising-banners/pull/1054

2022-10-12 04:27 UTC, Abban commented
The styles for the multistep form might change when implemented into the mobile banners whiuch will require them to be updated here, so don't merge this yet

2022-10-12 08:19 UTC, gbirke approved these changes

2022-10-12 08:44 UTC, merged