Desktop WPDE 01
wmde/fundraising-banners-until-2022 pull request #1069
Opened 2022-10-11 07:09 UTC by Abban

Convert last year's test 03 to the new structure

2022-10-19 11:14 UTC, gbirke requested changes
The VAR banner is slightly bigger than the CTRL, with a lot of whitespace on the 2nd page

2022-10-20 06:15 UTC, Abban commented
>The VAR banner is slightly bigger than the CTRL, with a lot of whitespace on the 2nd page

Good catch, I had a hardcoded padding value on the form. Fixed by https://github.com/wmde/fundraising-banners/pull/1091

2022-11-02 07:56 UTC, Sperling-0 reviewed
"The VAR banner is slightly bigger than the CTRL, with a lot of whitespace on the 2nd page" : This issue persists on my Chromium browser. However no such issue when using Firefox.

2022-11-04 17:33 UTC, moiikana commented on banners/wpde_desktop/styles/Banner.pcss
> +		border: 8px solid $color-primary;
the styling elements here would go to the themes, right?

2022-11-04 17:34 UTC, moiikana commented
the `variant-wpde-desktop.pcss` will become a theme next? or what is the purpose of it in the theme?

2022-11-11 14:25 UTC, gbirke approved these changes

2022-11-14 07:57 UTC, Abban commented
> the variant-wpde-desktop.pcss will become a theme next? or what is the purpose of it in the theme?

There was a few little differences between the WPDE banner and the iPad one that use the same theme. An entire variant for those things felt like overkill so I stuck it into that file

2022-11-23 13:11 UTC, merged