C22_WMDE_Test_12
wmde/fundraising-banners-until-2022 pull request #1125
Opened 2022-11-14 14:05 UTC by Abban

VAR banner implements new Subscription Form

Ticket: https://phabricator.wikimedia.org/T323021

2022-11-16 13:43 UTC, gbirke requested changes

2022-11-16 13:43 UTC, gbirke commented on banners/desktop/banner_var.js
> +		translations: Object.assign( Translations, LocalTranslations, TranslationsSoftClose, TranslationsSubscriptionForm ),
If softclose is now a permanently accepted feature in banners, we should merge it into local translations

2022-11-16 13:43 UTC, gbirke commented on components/SubscriptionForm/SubscriptionForm.jsx
> +			.toLowerCase()
Your regex does not distinguish between cases, to the `.toLowerCase()` is unneccessary IMHO. However, the user could accidentally type a space at the bginning or end of the email which would lead to hard-to-discover validation errors with your regex, so I recommend adding a `.trim()` (and testing if our transpiler replaces `trim` with an IE-compatible version and if not, stripping leading and training whitespace with [a manual polyfill](https://gist.github.com/arturotena/22158dcabe386bbfc536)

2022-11-16 14:28 UTC, Abban commented on banners/desktop/banner_var.js
> +		translations: Object.assign( Translations, LocalTranslations, TranslationsSoftClose, TranslationsSubscriptionForm ),
I quite like them separated like this as it's easier to know what's what. Maybe keep them in separate files and move them into a subfolder?

2022-11-16 14:29 UTC, Abban commented on components/SubscriptionForm/SubscriptionForm.jsx
> +			.toLowerCase()
Seems to work fine with IE11

2022-11-17 17:19 UTC, gbirke commented on banners/desktop/banner_var.js
> +		translations: Object.assign( Translations, LocalTranslations, TranslationsSoftClose, TranslationsSubscriptionForm ),
Yeah, maybe having default translations for features like soft close or the 2nd steps of the donation form is a good idea. Then they are cleanly separated and can still be overridden by LocalTranslations (which should come at the very end of that list)

2022-11-17 17:19 UTC, gbirke approved these changes

2022-11-19 07:22 UTC, Abban commented on banners/desktop/banner_var.js
> +		translations: Object.assign( Translations, LocalTranslations, TranslationsSoftClose, TranslationsSubscriptionForm ),
I'm gonna move the defaults in with the component

2022-11-19 08:05 UTC, merged