C22_WMDE_Test_15
wmde/fundraising-banners-until-2022 pull request #1137
Opened 2022-11-24 13:39 UTC by Sperling-0

2022-11-24 16:38 UTC, moiikana approved these changes

2022-11-25 14:33 UTC, moiikana requested changes

2022-11-25 14:33 UTC, moiikana commented on package-lock.json
> +        "fundraising-frontend-content": "github:wmde/fundraising-frontend-content#test",
should get switched back to production again right?
```suggestion
        "fundraising-frontend-content": "github:wmde/fundraising-frontend-content#production",
```

2022-11-28 11:41 UTC, Abban approved these changes

2022-11-28 11:50 UTC, merged