Allow delay handling via query params
wmde/fundraising-banners-until-2022 pull request #1139
Opened 2022-11-25 17:53 UTC by moiikana

https://phabricator.wikimedia.org/T323691

2022-11-29 10:30 UTC, gbirke requested changes
Thank you for doing this, it works 100% like specified in the ticket.

Unfortunately I did not update the ticket after we talked in the daily about adding a `devMode` parameter (that would also set the event fire rate to 100%). So that would be one small change - to rename `noDelay` to `devMode`.

If you want to do further cleanup, you could make `getBannerDelay` a function, dropping the dependency on `bannerContainer`. The only place where that is used is for the dev banner, `B17WMDE_webpack_prototype`. We could replace that mechanism with adding `&devMode` to all URLs in `campaign_info.toml`. I know it's a change that touches all banners again and will do it myself if you don't want to do it.

2022-11-29 10:30 UTC, gbirke commented on shared/banner_delay.js
> +		const parameters = url.split( '?' )[ 1 ];
```suggestion
		const parameters = window.location.search;
```

2022-11-29 10:30 UTC, gbirke commented on shared/banner_delay.js
> +		if ( parameters.includes( '&noDelay' ) ) {
```suggestion
		if ( parameters.match( /&noDelay/ ) ) {
```

`string.includes` is a modern feature where either our transpiler would add polyfill code for IE or IE would break.

2022-11-30 15:41 UTC, moiikana commented
>The only place where that is used is for the dev banner, B17WMDE_webpack_prototype. We could replace that mechanism with adding &devMode to all URLs in campaign_info.toml.

I can add `&devMode` at the end of every preview_link in the campaign_info.toml, yes,
but I think `this.bannerContainer.dataset.delay` was taking care of that local banner development delay (1) anyway.

The purpose of this PR is also to make something like 
`https://de.wikipedia.org/?banner=B22_WMDE_Test_04_var&devMode`
available for Kai for acceptance testing, right?

2022-12-01 10:19 UTC, gbirke approved these changes
I was thinking of dropping

2022-12-01 10:19 UTC, gbirke commented on shared/banner_delay.js
> +	if ( parameters.match( /&noDelay/ ) ) {
```suggestion
	if ( parameters.match( /&devMode/ ) ) {
```

2022-12-01 10:19 UTC, gbirke commented on shared/banner_delay.js
> +	}
With `devMode` in the campaign_info.toml, you can now completely drop `bannerContainer` as a parameter and in this check.

2022-12-06 10:19 UTC, gbirke approved these changes

2022-12-06 10:38 UTC, merged