C22_WMDE_Mobile_EN_Test_02
wmde/fundraising-banners-until-2022 pull request #1149
Opened 2022-12-05 16:52 UTC by moiikana

https://phabricator.wikimedia.org/T324444

2022-12-07 11:39 UTC, gbirke requested changes

2022-12-07 11:39 UTC, gbirke commented on banners/mobile_english/styles/theme_overrides_ctrl.pcss
> +}
I figured out how to override the theme file without using `!important`

1. Use the same nesting rules as in the original files. Apparently, PostCSS puts the non-nested classes at the top and then adds the concatened classes from nested rules after, regardless of the order in the file.
2. Use the media query, it adds specificity and overrides previous rules

```suggestion
.wmde-banner {
   &-navigation-wrapper {
	padding-bottom: 57px;
	@media ( min-width: $breakpoint-phone-s ) {
			padding-bottom: 57px;
	}
   }
}
```

2022-12-07 11:39 UTC, gbirke commented on banners/mobile_english/styles/theme_overrides_var.pcss
> +}
Please change these rules as well

2022-12-12 11:39 UTC, moiikana commented
rebased main

2022-12-17 17:59 UTC, gbirke approved these changes

2022-12-19 14:22 UTC, merged