[WIP] Create Mobile banner with sliding functionality
wmde/fundraising-banners-until-2022 pull request #115
Opened 2018-04-24 08:54 UTC by aniansson

2018-04-26 09:17 UTC, tzhelyazkova requested changes
I believe npm-debug.log shouldn't be part of the changes.
Is package-lock.json needed? I see two new dependencies are added to package.json, which means upon npm install those will be cleanly installed and not updated. Therefor, it seems package-lock.json shouldn't be part of the PR, or at least not with all of the 178 new lines of code.

2018-04-26 11:34 UTC, tzhelyazkova commented on prototype/banner_ctrl.js
> +require( './css/styles.pcss' );
Please put all the require statements at the top followed by the import statements and then all other declarations and logic.

2018-04-30 15:06 UTC, tzhelyazkova approved these changes

2018-05-04 08:04 UTC, gbirke commented on campaign_info.toml
> +
Maybe link to https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

2018-05-07 14:17 UTC, gbirke approved these changes

2018-05-07 14:21 UTC, merged