Only show banners on article namespace
wmde/fundraising-banners-until-2022 pull request #1160
Opened 2022-12-12 11:45 UTC by Abban

Ticket: https://phabricator.wikimedia.org/T324770

2022-12-14 15:50 UTC, gbirke requested changes

2022-12-14 15:50 UTC, gbirke commented on shared/banner_presenter.js
> +		if ( onMediaWiki() && mw.config.values.wgNamespaceNumber !== 0 && mw.config.values.wgNamespaceNumber !== 4 ) {
Please move this condition to a function like `isArticlePage` or `isWikipediaArticlePage`. Those namespaces are just an implementation detail

2022-12-14 15:50 UTC, gbirke commented on campaign_info.toml
> +preview_link = "/en-mobile/wiki/German_Wikipedia?devbanner={{banner}}&useskin=minerva&banner=B17WMDE_webpack_prototype&devMode"
I don't understand why this is necessary and it makes the preview slightly inconsistent. Could you leave it as-is or would it break something?

2022-12-14 15:50 UTC, gbirke commented on shared/event_logging_tracker.js
> +	trackNamespaceEvent( dimensionData, trackingRatio = 1 ) {
We want to track when a banner was not show because it was in the "wrong" namespace, or a "namespace where no banners are allowed". Could you rename this to something like `trackNamespacePreventedBannerDisplayEvent`, `trackNoBannerShownInNamespaceEvent`, or `trackBannerNotAllowedInNamespaceEvent`? I'm thinking of our future selves wondering what a "namespace event" is and having to jump from this implementation to the docblock in the interface ...

2022-12-16 07:28 UTC, Abban commented on campaign_info.toml
> +preview_link = "/en-mobile/wiki/German_Wikipedia?devbanner={{banner}}&useskin=minerva&banner=B17WMDE_webpack_prototype&devMode"
Oh, that was a left over from testing. Thanks for spotting it.

2022-12-16 10:50 UTC, gbirke approved these changes

2022-12-21 11:52 UTC, moiikana commented
rebased main

2022-12-21 12:03 UTC, merged