[WIP] Add improvements to c18 banners
wmde/fundraising-banners-until-2022 pull request #120
Opened 2018-06-28 16:17 UTC by tzhelyazkova

Feature: T197952 T197963

2018-06-29 12:50 UTC, gbirke requested changes

2018-06-29 12:50 UTC, gbirke commented on desktop/banner_ctrl.js
> +		} );
What was your reasoning behind putting the creation of the new event handler into the event handler when a predefined amount is selected?

I think the call to `appendEuroSign` is better suited be put in the `amount:custom` event handler.

2018-06-29 12:50 UTC, gbirke commented on desktop/banner_ctrl.js
> +		$( field ).val( $( field ).val() + ' €' );
Unfortunately, adding the sign to the value of the input field breaks the in-banner validation. It might also create invalid input for the FundraisingFrontend, when the field value is sent to it.

Since input fields are not container (and hence we can't use `:after` CSS rules), the euro sign requirement becomes more difficult. I see three options going forward:
* Remove euro sign on form submission (before validation). If validation does not pass, add it back.
* Add an euro-sign overlay that is positioned according to the content of the input field. Don't know if it's possible to center that properly.
* Add an Euro-Sign overlay/sister element that is positioned right to the input field.

2018-06-29 13:08 UTC, tzhelyazkova commented on desktop/banner_ctrl.js
> +		} );
That was a mistake, it should definitely be in `amount:custom` event handler.

2018-07-05 16:19 UTC, gbirke approved these changes

2018-07-10 10:04 UTC, timEulitz commented
`tracking_events.js` is failing purposefully since the click events are not working right now. Undo changes marked by `TODO` before merging.

2018-07-12 14:35 UTC, merged