Progress bar on mobile banner
wmde/fundraising-banners-until-2022 pull request #214
Opened 2018-12-16 20:17 UTC by tzhelyazkova

2018-12-16 21:51 UTC, timEulitz commented
I have pushed some more improvements which should resolve the issues for lower resolutions. Before merging we should clean up the old progress bar code and use this for all banners but I will double-check with Kai on that.

2018-12-17 12:38 UTC, gbirke requested changes
The right text looks a bit weird, as if a separator was missing. My proposal:

> Nur noch x Tage, es fehlen noch y Mio."

We should reintroduce the rounded corners of the progress bar, at the moment it looks a bit "cut off".

2018-12-18 10:50 UTC, tzhelyazkova commented on shared/progress_bar/style_mobile.pcss
> +	flex-wrap: wrap;
hm, why? That will make the text split in two rows which is not what we want, right? (at least according to the mock)

2018-12-18 11:37 UTC, gbirke approved these changes

2018-12-18 11:48 UTC, merged