C19 wmde test 06
wmde/fundraising-banners-until-2022 pull request #244
Opened 2019-10-09 13:18 UTC by tzhelyazkova

Feature: [T234441](https://phabricator.wikimedia.org/T234441)

This campaign's banners are based on an old 2018 banner (`ctrl` from test 24).
This is why the usual commit structure we have doesn't apply.

Please double check the German text in the infobox as I was blindly copy/pasting. :de: :sweat_smile:

2019-10-10 07:54 UTC, gbirke requested changes
Please change the param and put the banners on CN so Tobias can test them

2019-10-10 07:54 UTC, gbirke commented on desktop/templates/banner_html_var.hbs
> +                      action="https://spenden.wikimedia.de/donation/new?piwik_campaign={{ CampaignName }}&piwik_kwd={{ BannerName }}&skin=2&fd=0">
Should be `fd=1`

2019-10-10 08:24 UTC, tzhelyazkova commented on desktop/templates/banner_html_var.hbs
> +                      action="https://spenden.wikimedia.de/donation/new?piwik_campaign={{ CampaignName }}&piwik_kwd={{ BannerName }}&skin=2&fd=0">
I'm dumb :rofl:

2019-10-10 15:25 UTC, ghost approved these changes

2019-10-11 10:57 UTC, gbirke approved these changes

2019-10-11 10:57 UTC, merged