Implement german Ipad banner with preact
wmde/fundraising-banners-until-2022 pull request #301
Opened 2020-01-14 14:23 UTC by moiikana

2020-01-15 18:14 UTC, gbirke requested changes
Two small changes are needed.

I'm torn on the `ui` and `ui/form` subfolder in `components`. It keeps consistency, but at the cost of deeply nested and confusing relative paths. What's more important to you?

2020-01-15 18:14 UTC, gbirke commented on pad_preact/components/ui/form/DonationForm.jsx
> +			action={ formAction }>
The campaign parameters (`props.bannerName` and `props.campaignName`) are missing.

2020-01-15 18:14 UTC, gbirke commented on pad_preact/components/ui/form/FormItemsBuilder.js
> +export default class FormItemsBuilder {
Since the other form items are 100% identical, please use inheritance here. This will make the class much shorter.

2020-01-15 18:14 UTC, gbirke commented on shared/messages/de.js
> +	'give-address-statement-negative': 'Nein'
The translations file is part of every banner, not only the iPad banner. Therefore, we should keep a certain discipline to mark translations that are part of an A/B test as such, to potentially clean up after the tets is done.

2020-01-16 14:18 UTC, gbirke requested changes

2020-01-16 14:18 UTC, gbirke commented on pad_preact/Banner.jsx
> +
Please remove the `FundModal` component and all state and state-changing methods from this banner. For iPad, the banner just displays a link.

2020-01-16 14:18 UTC, gbirke commented on pad_preact/Banner.jsx
> +	}
I'm not sure what's worse - an incomplete list of available properties or no list of properties at all. What do you think?

2020-01-16 14:18 UTC, gbirke commented on pad_preact/Banner_var.jsx
> +}
Please delete `Banner_var.jsx`, that's unneccessary duplication. Instead, load different form components and pass in the form component as a property (like we do for BannerText)

2020-01-16 14:18 UTC, gbirke commented on shared/messages/de.js
> +	// the following 2 lines are only for the ipad var test, remove if not in use anymore
👍

2020-01-16 14:18 UTC, gbirke commented on pad_preact/styles/styles_ctrl.pcss
> +@import '../../shared/components/ui/FundsModal.pcss';
You can remove this line, as we don't have a FundsModal here

2020-01-16 14:48 UTC, moiikana commented on pad_preact/Banner.jsx
> +	}
would a complete list of properties in this case be the following? (+their respective types) : 
- trackingIds: ,
- campaignParameters: ,
- campaignProjection: ,
- formatters: ,
- bannerText: ,
- donationForm: ,
- translations: ,
- formItems:
- trackingData: this.trackingData,
- impressionCounts:,
- onClose: PropTypes.func,
- registerDisplayBanner: PropTypes.func.isRequired

these are the properties from banner_ctrl.js, banner_presenter.js and Banner.jsx.
I think it would be nice to have them documented like this, if this list is complete and correct.

2020-01-16 16:01 UTC, moiikana commented on pad_preact/Banner.jsx
> +		campaignParameters: PropTypes.object,
I tried to accumulate the propTypes that are passed down to the Banner class by banner_ctrl.js, banner_presenter and so on..
Is it correct that they all should be defined here? (they are used here, so maybe yes..)
I tried to give them the most fitting type and tried to check my guessings with `console.log(typeof ....)` , but that always told me it's either an object or a func. I'm also not sure about whether it could be PropTypes.elementType or .element in line 23-24.

2020-01-16 16:28 UTC, gbirke commented on pad_preact/Banner.jsx
> +		donationForm: PropTypes.elementType, //func?
`elementType` is exactly right. Elements can be either functions or classes.

2020-01-16 16:28 UTC, gbirke commented on pad_preact/Banner.jsx
> +		formItems: PropTypes.object,
```suggestion
                /**
                   *  Contains items with values and labels for SelectGroup components 
                   *  in the form, e.g. amounts, payment types, intervals, etc 
                   */
		formItems: PropTypes.object,
```

2020-01-16 16:28 UTC, gbirke commented on pad_preact/Banner.jsx
> +		registerDisplayBanner: PropTypes.func.isRequired
```suggestion
                /** Callback to register a displayBanner function with the BannerPresenter */
		registerDisplayBanner: PropTypes.func.isRequired
```

2020-01-16 16:28 UTC, gbirke commented on pad_preact/Banner.jsx
> +		/** complex object that holds any data needed for tracking purposes */
```suggestion
		/** object that holds any data needed for tracking purposes */
```

2020-01-16 16:28 UTC, gbirke commented on pad_preact/Banner.jsx
> +		campaignParameters: PropTypes.object,
Thank you so much! 

Two props are missing: `bannerName` and `campaignName` (coming from `...trackingIds`) in the entry point.

2020-01-20 09:56 UTC, merged