Implement english ipad banners with preact
wmde/fundraising-banners-until-2022 pull request #303
Opened 2020-01-20 16:17 UTC by moiikana

https://phabricator.wikimedia.org/T243208

2020-01-21 15:57 UTC, gbirke requested changes
Thank you for that expressive commit message, our future selves will be very happy about that.

2020-01-21 15:57 UTC, gbirke commented on pad_english_preact/components/ui/Footer.jsx
> +					href="https://spenden.wikimedia.de/use-of-funds?skin=0&piwik_campaign={{ CampaignName }}&piwik_kwd={{ BannerName }}_link">
You need to build the proper link URL (`campaignName` and `bannerName` must come from props).

2020-01-21 15:57 UTC, gbirke commented on pad_english_preact/components/ui/Footer.jsx
> +}
The difference between the two footers is the "Application of Funds" behavior - either showing a modal box or going to a new page. To reduce duplication I'd prefer one shared footer with a `showFundsModal` prop. We either pass an event handler into `showFundsModal` (that toggles the modal and calls `e.preventDefault()` on the original event) or an empty function. The empty function won't do anything and browser will execute the original behavior of the link - opening a new page.

2020-01-21 15:57 UTC, gbirke commented on pad_english_preact/components/BannerText_var.jsx
> +}
This function is not needed in these BannerText instances, please remove it from both.

2020-01-21 15:57 UTC, gbirke commented on shared/components/ui/LanguageWarningBox.jsx
> +}
Since the `LanguageWarningBox` is only shown in English banners, we could gain some readability and save a few bytes and CPU cycles by removing `TranslationContext ` and putting the string directly in here.

2020-01-21 16:01 UTC, gbirke commented on pad_english_preact/components/ui/Footer.jsx
> +					<span>Spendenkonto Wikimedia Foerdergesellschaft</span>
In the new shared footer the word "Spendendkonto" must be translatable, it's 'DONATION ACCOUNT' ( poabbly uppercased with CSS) in the old english iPad banner

2020-01-21 16:07 UTC, moiikana commented on pad_english_preact/components/ui/Footer.jsx
> +					href="https://spenden.wikimedia.de/use-of-funds?skin=0&piwik_campaign={{ CampaignName }}&piwik_kwd={{ BannerName }}_link">
when will I ever notice this beforehand ...🤦‍♂️ thx

2020-01-23 14:23 UTC, gbirke approved these changes

2020-01-23 14:23 UTC, merged