Implement English Mobile Preact banner
wmde/fundraising-banners-until-2022 pull request #309
Opened 2020-02-25 16:00 UTC by moiikana

2020-03-02 15:44 UTC, gbirke requested changes
Some changes here will break now when #310 is applied, I suggest applying #310 first and then rebasing this.

2020-03-02 15:44 UTC, gbirke commented on mobile_english_preact/components/BannerText.jsx
> +			{ campaignDaySentence.getSentence() } We depend on donations averaging about € 23.83, but 99% of our readers don't give.
See #310 for the changed `getSentence` code
```suggestion
			{ campaignDaySentence } We depend on donations averaging about € 23.83, but 99% of our readers don't give.
```

2020-03-02 15:44 UTC, gbirke commented on mobile_english_preact/components/FollowupTransition.jsx
> +export default class BannerTransition extends Component {
Is this transition different than the one in Mobile? If not, please move it to shared instead.

2020-03-02 15:44 UTC, gbirke commented on mobile_english_preact/styles/SelectGroup.pcss
> +	.select-group-container--interval {
Please add the `select-` prefix from #310 to the 3 container selectors

2020-03-02 15:44 UTC, gbirke commented on pad_english_preact/components/BannerText.jsx
> +			<span> { campaignDaySentence.getSentence() } We depend on donations averaging about €&nbsp;23.83, but 99% of our readers
```suggestion
			<span> { campaignDaySentence } We depend on donations averaging about €&nbsp;23.83, but 99% of our readers
```

2020-03-02 15:44 UTC, gbirke commented on pad_english_preact/components/BannerText_var.jsx
> +			<span> { campaignDaySentence.getSentence() } We depend on donations averaging about €&nbsp;23.83, but 99% of our readers
```suggestion
			<span> { campaignDaySentence } We depend on donations averaging about €&nbsp;23.83, but 99% of our readers
```

2020-03-02 15:44 UTC, gbirke commented on mobile_english_preact/components/MiniBanner.jsx
> +						formattedGoalDonationSumNumeric: props.formatters.millionFormatterNumericOnly( campaignProjection.goalDonationSum / 1000000 ),
IMHO the JSX fieles should contain as few logic as possible. Withe formatters (and esp. with a name like `millionFormatterNumericOnly`) it makes sense to move the division into thze formatter.

2020-03-02 15:44 UTC, gbirke commented on shared/number_formatter/de.js
> +export const millionFormatterNumericOnly = formatter( { round: 1, decimal: ',', padRight: 1 } );
```suggestion
export const millionFormatterNumeric = formatter( { round: 1, decimal: ',', padRight: 1 } );
```

2020-03-02 15:44 UTC, gbirke commented on shared/number_formatter/en.js
> +export const millionFormatterNumericOnly = formatter( { round: 1, padRight: 1 } );
```suggestion
export const millionFormatterNumeric = formatter( { round: 1, padRight: 1 } );
```

2020-03-03 11:56 UTC, moiikana commented on pad_english_preact/components/BannerText.jsx
> +			<span> { campaignDaySentence.getSentence() } We depend on donations averaging about €&nbsp;23.83, but 99% of our readers
yes to the function call removal, 
but that "<span> " needs to stay there for having a space before the campaigndaysentence (because preact autoremoves them).

2020-03-03 17:04 UTC, gbirke approved these changes

2020-03-04 13:18 UTC, merged