Unify custom amount field
wmde/fundraising-banners-until-2022 pull request #311
Opened 2020-03-06 12:46 UTC by Abban

https://phabricator.wikimedia.org/T244714

2020-03-09 08:56 UTC, moiikana reviewed
I approve this but would like to have @gbirke 's opinion on the SelectCustomAmount.jsx class, about whether there might have been more preact-optimized ways to handle the user events or if this is totally fine.

2020-03-09 10:13 UTC, gbirke requested changes

2020-03-09 10:13 UTC, gbirke commented on shared/number_formatter/de.js
> +export const customAmountInputFormatter = formatter( { round: 2, decimal: ',', integerSeparator: '' } );
When we drop the old-style banners we can also drop the `amountInputFormatter`. Please add a `/** @deprecated */` comment to the `amountInputFormatter` to remind us and avoid future confusion over which one to use.

2020-03-09 10:13 UTC, gbirke commented on shared/components/ui/form/SelectCustomAmount.jsx
> +		this.radioInput.current.click();
Have you tried setting the `checked` attribute of the input tag based on the current state? References and native DOM elements should be a last resort.

2020-03-09 10:13 UTC, gbirke commented on shared/components/ui/form/SelectCustomAmount.jsx
> +
I'm torn on the implementation. I'd have liked it more if `SelectCustomAmount` had stayed stateless and the blur and value changes and the euro sign would be implemented purely with CSS (see https://spenden.wikimedia.de/ ). The performance would be better and it would be less code. OTOH the JavaScript makes the behavior (or at least the intended styling "hooks" (i.e. CSS classes) very explicit and more readable.

This is not a "please change" recommendation, more like a reminder to use CSS instead of JS if possible.

2020-03-09 13:00 UTC, Abban commented on shared/components/ui/form/SelectCustomAmount.jsx
> +		this.radioInput.current.click();
Yes, I found that it had a weird behaviour where it added the attribute onto the element in the DOM and prevented the user from being able to select the other radio options.

2020-03-09 13:09 UTC, Abban commented on shared/number_formatter/de.js
> +export const customAmountInputFormatter = formatter( { round: 2, decimal: ',', integerSeparator: '' } );
Is there a preferred style for this? In front of the variable, like a docblock or trailing at the end of the line like in CSS?

2020-03-09 13:14 UTC, Abban commented on shared/components/ui/form/SelectCustomAmount.jsx
> +
Yeah this was a tricky one, some of the required behaviour of the euro symbol depends on js (keeping it visible when the field has a value) so I decided to keep the code that controls that together rather than split it between js/css.

2020-03-09 13:29 UTC, gbirke commented on shared/number_formatter/de.js
> +export const customAmountInputFormatter = formatter( { round: 2, decimal: ',', integerSeparator: '' } );
Like a docblock

2020-03-11 11:23 UTC, gbirke approved these changes

2020-03-11 11:24 UTC, merged