C20 wmde mobile test 01
wmde/fundraising-banners-until-2022 pull request #346
Opened 2020-08-05 08:31 UTC by Abban

https://phabricator.wikimedia.org/T259461

2020-08-05 13:42 UTC, moiikana reviewed
in my desktop test 03 PR I moved the new footer to shared...EasySelectFooter.jsx
maybe you could do that here, too

2020-08-05 15:59 UTC, gbirke requested changes

2020-08-05 15:59 UTC, gbirke commented on shared/banner_slider.js
> +		if ( !this.sliderAutoPlaySpeed ) {
The doc comment for the constructor says that it's an `int`, so this was immediately confusing to me. I'd rather not repeat the laissez-faire typing done by Flickity. 

I can think of two options to change this:

* change the constructor docblock to document the type to `{int|false}` (don't know if that's even a valid type) and explain what `false` means or
*  explain the special value `0` in the constructor docblock and cast to boolean in `initialize`, depending on the param being 0 or > 0

Choose whatever feels less wrong to you.

2020-08-05 15:59 UTC, gbirke commented on mobile/banner_var.js
> +	bannerContainer.dataset.delay || 7500,
Plz ask our PM if 7.5 seconds is standard across banners. AFAIR the default dealy was always 5 seconds for mobile.

2020-08-06 07:39 UTC, Abban commented on shared/banner_slider.js
> +		if ( !this.sliderAutoPlaySpeed ) {
Thinking about it the Slider object probably shouldn't care about the autoplay speed there anyway. I'll add a prop higher up the tree.

2020-09-21 13:06 UTC, merged