Prepare campaign for B20_WMDE_Test_07
wmde/fundraising-banners-until-2022 pull request #367
Opened 2020-09-30 05:49 UTC by Abban

https://phabricator.wikimedia.org/T263411
https://phabricator.wikimedia.org/T263408

2020-09-30 08:14 UTC, gbirke requested changes

2020-09-30 08:14 UTC, gbirke commented on desktop/components/ui/form/DonationFormWidthInfoHeader.jsx
> +		source: Symbol.keyFor( props.bannerType )
I guess you intended this to be the parameter that triggers the A/B test on the donation page, but that's not how it works. To provide such a parameter, you need to use the `url_key` from the campaign configuration as the param name and the bucket index (0 or 1) as the value. For this test have a look at the campaign config created in https://github.com/wmde/FundraisingFrontend/pull/1878 
The param name is called `provadd`

2020-09-30 08:14 UTC, gbirke commented on desktop/Banner.jsx
> +	VAR: Symbol.for( 'var' )
We don't want global symbols from our banners. Please create a different method for mapping banner types to bucket testing values.

2020-09-30 15:31 UTC, gbirke approved these changes

2020-10-09 08:56 UTC, moiikana commented on desktop/components/ui/form/DonationFormWidthInfoHeader.jsx
> +
cool :sunglasses:

2020-10-12 10:08 UTC, merged