Prepare campaign for C20_WMDE_Mobile_Test_03
wmde/fundraising-banners-until-2022 pull request #368
Opened 2020-09-30 10:45 UTC by Abban

2020-10-02 18:38 UTC, gbirke requested changes

2020-10-02 18:38 UTC, gbirke commented on mobile/components/ui/form/DonationFormWithHeaders_var.jsx
> +		const piwick = '?piwik_campaign=' + props.campaignName + '&piwik_kwd=' + props.bannerName;
Could you change the name of this variable to `tracking`?

2020-10-02 18:38 UTC, gbirke commented on mobile/components/ui/form/DonationFormWithHeaders_var.jsx
> +		if ( e.target.value !== AddressType.FULL.value ) {
could you switch this condition around to make it easier to read?

2020-10-02 18:38 UTC, gbirke commented on mobile/components/ui/form/DonationFormWithHeaders_var.jsx
> +			action={ getFormAction() }>
While this works, calling functions feels inconsistent to me. Maybe make formAction a reactive state and change it in `onChangeAddressType`?

2020-10-02 18:38 UTC, gbirke commented on mobile/components/ui/form/DonationFormWithHeaders_var.jsx
> +				impressionCounts={ props.impressionCounts }
you need to add the `addressType={ addressType }` property here.

`SubmitValues` already has that property, no need to change it.

2020-10-02 18:38 UTC, gbirke commented on mobile/components/ui/form/DonationFormWithHeaders_var.jsx
> +	let [ disabledAddressTypes, setDisabledAddressTypes ] = useState( [] );
```suggestion
	const [ disabledAddressTypes, setDisabledAddressTypes ] = useState( [] );
```

2020-10-05 05:36 UTC, Abban commented on mobile/components/ui/form/DonationFormWithHeaders_var.jsx
> +			action={ getFormAction() }>
I think the issue with that is the initial value when the ref is created. It would have to call the same function to get it eg:

`const [ formAction, setFormAction ] = useState( getFormAction() );`

Then if we did that we'd also do it in `onChangeAddressType`:

```js
const onChangeAddressType = e => {
	setAddressType( e.target.value );
	setFormAction( getFormAction() ); 
...
);
```
So what we end up with is the same function and an extra ref.

2020-10-12 19:11 UTC, gbirke commented on mobile/components/ui/form/DonationFormWithHeaders_var.jsx
> +			action={ getFormAction() }>
After revisiting this, I think it's fine. I think my brain was in Vue mode when I wrote my comment, where reactive state would have been better. In this case, it's totally fine.

2020-10-13 09:47 UTC, gbirke approved these changes

2020-10-19 06:08 UTC, merged