dewiki-test-10
wmde/fundraising-banners-until-2022 pull request #38
Opened 2017-10-17 15:17 UTC by KaiNissen

This is for [phab:T177600](https://phabricator.wikimedia.org/T177600).

2017-10-18 08:21 UTC, JeroenDeDauw commented
+1

2017-10-19 08:20 UTC, wiese requested changes
The var behavior is fine, I believe.

Conceptual concern: doesn't the ctrl require the `pmt=0` GET-parameter?

2017-10-19 08:20 UTC, wiese commented on desktop/banner_var.js
> +// require( './css/styles.pcss' );
Not a hard objection, but for mobile (#37) I went the way of _not_ duplicating the ctrl CSS but create a file for var that contains only the delta and load both.

2017-10-19 09:02 UTC, wiese approved these changes

2017-10-26 12:25 UTC, merged