Prepare campaign for C20_WMDE_mobile_en_test_01
wmde/fundraising-banners-until-2022 pull request #412
Opened 2020-11-02 09:34 UTC by moiikana

- first mobile EN test 2020
- introduces rightText changes for progress bar
- progress bar animation starts

- VAR: introduces address provision options (where already
implemented in DE mobile 03 2020)

https://phabricator.wikimedia.org/T266756

2020-11-02 17:02 UTC, Abban requested changes
Looking good!

One other thing I noticed apart from the comments is that the progressbar slide should be the first one in each banner.

2020-11-02 17:02 UTC, Abban commented on campaign_info.toml
> +pagename = "B19WMDE_mob_en01_201103_ctrl"
This should probably be B20?

2020-11-02 17:02 UTC, Abban commented on shared/components/ui/Infobox.jsx
> +	const visitorsVsDonorsSentence = new VisitorsVsDonorsSentence( campaignParameters, campaignProjection, campaignDays, Translations );
This is much better than the implementation I did in the [.de banner](https://github.com/wmde/fundraising-banners/pull/402/files#diff-ede34ae6ca87afb22d9a78f593fc2397722bdf86f33bc880b511fe1ee54a1249R7).

As a rule I would pass in only the things the VisitorsVsDonorsSentence class needs to know about though, it doesn't need to know anything about the other objects:

```js
const visitorsVsDonorsSentence = new VisitorsVsDonorsSentence(
    campaignParameters.millionImpressionsPerDay,
    campaignProjection.getProjectedNumberOfDonors(),
    campaignDays.getDaysSinceCampaignStart(),
    Translations[ 'visitors-vs-donors-sentence' ]
);
```

2020-11-02 18:31 UTC, moiikana commented on campaign_info.toml
> +pagename = "B19WMDE_mob_en01_201103_ctrl"
goddammit

2020-11-02 18:34 UTC, moiikana commented on shared/components/ui/Infobox.jsx
> +	const visitorsVsDonorsSentence = new VisitorsVsDonorsSentence( campaignParameters, campaignProjection, campaignDays, Translations );
aah.. that's much easier indeed

2020-11-03 07:10 UTC, Abban approved these changes
Looks good! Probably should wait and see how we're adding use of funds before merging though.

2020-11-03 08:04 UTC, merged