[WIP] T173919 Implement english banner
wmde/fundraising-banners-until-2022 pull request #45
Opened 2017-11-06 10:45 UTC by gbirke

2017-11-24 16:34 UTC, wiese commented on desktop/templates/banner_text_var.hbs
> +<<<<<<< HEAD
Is that good?

2017-11-27 08:59 UTC, wiese requested changes
Mind the unresolved merge conflict!

2017-11-27 08:59 UTC, wiese commented on desktop/banner_ctrl.js
> +		$( '#WMDE_Banner' ).trigger( 'validation:period:error', Translations[ 'no-interval-message' ] );
Here we change both, the translation (understandable) as well as the mechanism to deploy it - switching from dedicated function to pure `$` feels like a deterioration. Is this intentional?

2017-11-27 13:26 UTC, KaiNissen commented on desktop/banner_ctrl.js
> +		$( '#WMDE_Banner' ).trigger( 'validation:period:error', Translations[ 'no-interval-message' ] );
Hm, I'm not sure whether it is better to hide `$` in the respective function. Might be a good idea for having the event handling in `BannerFunctions` only, though.

In my opinion, what happens in `BannerFunctions` should be dropped/extracted into modules over time anyway. In this case we should add an `EventManager` that cares for handling all events.

2017-11-29 09:09 UTC, wiese approved these changes

2017-11-29 18:25 UTC, merged