Desktop-wpde-03
wmde/fundraising-banners-until-2022 pull request #787
Opened 2021-12-09 14:13 UTC by Abban

2021-12-15 13:36 UTC, moiikana approved these changes

2021-12-15 13:38 UTC, moiikana commented on shared/components/ui/ProgressBar.jsx
> -			if ( props.daysLeft > 14 ) {
not so sure if it's fine to delete this in the shared progress bar, but maybe you've already talked about that

2021-12-15 14:26 UTC, Abban commented on shared/components/ui/ProgressBar.jsx
> -			if ( props.daysLeft > 14 ) {
No we didn't talk about it at all! I think that we should be manually hiding the text with css anyway instgead of having it automatically appear.

We actually should check the existing banners that are going to have that text appear at the weekend and make sure it's styled though!

2021-12-15 16:24 UTC, moiikana requested changes
might be missing the footer

2021-12-16 15:52 UTC, moiikana approved these changes

2021-12-16 16:01 UTC, merged